# Default values for voting-app-helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  serviceAccountName: default

worker:
  replicaCount: 1

  image:
    repository: mycluster.icp:8500/default/worker
    tag: 0.1.0
    pullPolicy: IfNotPresent

vote:
  replicaCount: 1

  image:
    repository: mycluster.icp:8500/default/vote
    tag: 0.1.1
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80

result:
  replicaCount: 1

  image:
    repository: mycluster.icp:8500/default/result
    tag: 0.1.0
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 80

db:
  dataPVC:
    name: db-pvc
    storageClassName: 
    useDynamicProvisioning: true
    accessMode: ReadWriteOnce
    size: 5Gi