apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
  namespace: vote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: mycluster.icp:8500/default/result:0.1.0
        name: result
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: registry-secret
